List<String> names = [
  "Sara sy",
  "Ahamd ahmad",
  "Osama Osama",
  "Hassan Hasan",
  "Abdullah kn",
  "Sara sy",
  "Ahamd ahmad",
  "Osama Osama",
  "Hassan Hasan",
  "Abdullah kn",
  "Sara sy",
  "Ahamd ahmad",
  "Osama Osama",
  "Hassan Hasan",
  "Abdullah kn",
];

List<String> images = [
  "images/demon_slayer.jpg",
  "images/saitama.jpg",
  "images/stray.png",
  "images/uchiha.jpg",
  "images/newspaper.jpg",
  "images/demon_slayer.jpg",
  "images/saitama.jpg",
  "images/stray.png",
  "images/uchiha.jpg",
  "images/newspaper.jpg",
  "images/demon_slayer.jpg",
  "images/saitama.jpg",
  "images/stray.png",
  "images/uchiha.jpg",
  "images/newspaper.jpg",
];
